#!/usr/bin/env bash

# trap interrupts and exit instead of continuing the loop
trap "printf \"\n\n\xE2\x9C\x96 Exited!\n\"; exit;" SIGINT SIGTERM

# install Homebrew if not installed
command -v brew >/dev/null 2>&1 || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install Imagemagick if not installed
command -v convert >/dev/null 2>&1 || brew install imagemagick

# create clean output folder
rm -rf output
mkdir -p output

# process each image in `input` directory
for filepath in ./input/*; do
	filename=$(basename "$filepath")
	filename="${filename%.*}"
	printf "Processing $filename..."
	convert -monochrome -strip -interlace Plane -gaussian-blur 0.05 -quality 85% -depth 1 -units PixelsPerInch -density 300 "$filepath" "output/$filename.tiff"
	printf "\tDone!\n"
done

# print success message and summary
count_output_files() {
	ls -1q output/* | wc -l | tr -d '[:space:]'
}
printf "\n\xE2\x9C\x94 Successfully processed $(count_output_files) images.\n"
